common/urls.py
# ---------------------------------- [edit] ---------------------------------- #
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
# ---------------------------------------------------------------------------- #

app_name = 'common'

urlpatterns = [
# ---------------------------------- [edit] ---------------------------------- #
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
# ---------------------------------------------------------------------------- #
]

config/urls.py
from django.contrib import admin
from django.urls import path, include #project url 받아서 다른 url로 넘길 때 사용

# ---------------------------------- [edit] ---------------------------------- #
from pybo import views
# ---------------------------------------------------------------------------- #

urlpatterns = [
    path('admin/', admin.site.urls),
# ---------------------------------- [edit] ---------------------------------- #
    path('pybo/', include('pybo.urls')),
# ---------------------------------------------------------------------------- #
    path('common/', include('common.urls')),

    path('', views.index, name='index'),  # '/'에 해당되는 path
]

pybo/urls.py
#url.py :
#실제 프론트가 요청을 보냈을 때 가장 먼저 어디로 보낼지 판단하는 곳이며 (클래스로 진입하기 위한 진입 메소드를 제공)
#근데 project와 app에 둘 다 urls.py가 있는데 그 둘 중 project에서 먼저 url을 받아서 어디로 갈지 결정. 그래서 project내의 urls.py에 include를 import하는 것
#프론트와 백의 연결 통로, 통신 통로

# ---------------------------------- [edit] ---------------------------------- #
from django.urls import path

from . import views

# ---------------------------------- [edit] ---------------------------------- #
app_name = 'pybo'
# ---------------------------------------------------------------------------- #

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name = 'detail'),
    # ---------------------------------- [edit] ---------------------------------- #
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # ---------------------------------------------------------------------------- #
    path( 'question/create/', views.question_create, name = 'question_create'),
]

templates/base.html
<!-- ------------------------------- [edit] -------------------------------- -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- ------------------------------- [edit] -------------------------------- -->
{% include "navbar.html" %}
<!-- ----------------------------------------------------------------------- -->
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- ------------------------------- [edit] -------------------------------- -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- ----------------------------------------------------------------------- -->
</body>
</html>

templates/form_errors.html
<!-- ------------------------------- [edit] -------------------------------- -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- ----------------------------------------------------------------------- -->

templates/navbar.html
<!-- ------------------------------- [edit] -------------------------------- -->
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <!-- ------------------------------- [edit] -------------------------------- -->
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <!-- ----------------------------------------------------------------------- -->
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
<!-- ----------------------------------------------------------------------- -->